### PR TITLE
updated graphics

### PR DESCRIPTION
**Pull request by Thomas-QM**
is better or worse

doge wonders

### CODE REVIEW

**Comment by spikespaz** [comment]
The shifty/glitchy text looks silly, I would like that to go away. Can you just create them again but with that underglow on all of them, without the fragmentation, and remove the chat logs from the background?

**Comment by Thomas-QM** [comment]
many feedback
such eye
much see
very agree
soon do

wow

**Comment by Thomas-QM** [comment]
made a new commit
did doge get what u said
or not
doge many wonder

**Comment by spikespaz** [comment]
Sorry but I still think the gradient looks ugly. I have updated the assets to a higher resolution in my fork, I will be merging that repo. IF you like, you can update your own fork and re-add the shadows, just use the white objects in the `alpha/` directory.

**Pull request closed without merging**
